name: AutoTestCI
on: push
jobs:
  build:
    name: AutoTest
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1 
    - name: prepare env
      run: |
        sudo apt-get update
        sudo apt-get -yqq install scons qemu git
        wget -q https://github.com/RT-Thread/toolchains-ci/releases/download/arm-2017q2-v6/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
        sudo tar xjf gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 -C /opt
        export RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-6-2017-q2-update/bin
        /opt/gcc-arm-none-eabi-6-2017-q2-update/bin/arm-none-eabi-gcc --version
        git clone https://github.com/armink/EasyFlashAutoTestBSP
        scons -j4 -C EasyFlashAutoTestBSP
    - name: startup ci
      run: |
        python3 qemu_runner.py --elf $PWD/EasyFlashAutoTestBSP/rtthread.elf --sd $PWD/EasyFlashAutoTestBSP/sd.bin
        cat rtt_console.log
